### ISSUE TITLE
请问有训练部署的教程不？

### ISSUE THREAD

**Issue by winktool** [shinkuan/kanachan.mjai.app#1]

**Comment by shinkuan** [comment]
原Kanachan作者在最近恢復了對mjai的支持，你可以看看。

- https://github.com/Cryolite/kanachan/tree/develop/mjai.app
- https://github.com/Cryolite/kanachan/pull/51

如果要使用我這個的話就是把model.kanachan放到model資料夾後，將以下檔案壓縮成zip檔案就行了：

- [model](https://github.com/shinkuan/kanachan.mjai.app/tree/main/model)
- [_kanachan.py](https://github.com/shinkuan/kanachan.mjai.app/blob/main/_kanachan.py)
- [bot.py](https://github.com/shinkuan/kanachan.mjai.app/blob/main/bot.py)
- [game.json](https://github.com/shinkuan/kanachan.mjai.app/blob/main/game.json)
- [hand_calculator.py](https://github.com/shinkuan/kanachan.mjai.app/blob/main/hand_calculator.py)

**Comment by winktool** [comment]
感恩～
我对AI领域了解不多，仅限于研究过谷歌验证码的挑战。
我想学习研究Kanachan。
但貌似需要先准备大量的牌谱，然后才能进行训练，我很好奇大家的数量级牌谱都是从何而来的。

**Comment by shinkuan** [comment]
> 我很好奇大家的数量级牌谱都是从何而来的。

我的牌譜是從牌譜屋抓下來的，要抓的話需要會一些爬蟲技術。

**Comment by winktool** [comment]
请问是这个吗？
[amae-koromo.sapk.ch](https://amae-koromo.sapk.ch/)。
是挑选人来抓取还是有通用接口呀？

**Comment by winktool** [comment]
[Mortsl](https://github.com/Equim-chan/Mortal)您有成功开始训练了不？

**Comment by shinkuan** [comment]
這個就要請你自己研究了。

另外有鑑於此issue已處理完畢，我現在將他關閉。

**Comment by winktool** [comment]
谢谢～
